---

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: social_media_development

test:
  <<: *default
  database: social_media_test

production:
  <<: *default
  database: social_media_production
  username: social_media
  password: <%= ENV['SOCIAL_MEDIA_DATABASE_PASSWORD'] %>
  DATABASE_URL: <%= SocialMedia::Config.database_url %>
